# Generated by Django 4.1.7 on 2023-02-20 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.SmallIntegerField()),
                ('text', models.TextField()),
                ('nickname', models.CharField(max_length=160)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.category')),
            ],
        ),
    ]
